package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAT_IMAGE.
 */
public class CatImage {

    private Long id;
    private String url;
    private Boolean favorite;

    public CatImage() {
    }

    public CatImage(Long id) {
        this.id = id;
    }

    public CatImage(Long id, String url, Boolean favorite) {
        this.id = id;
        this.url = url;
        this.favorite = favorite;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

}
