package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAT_POST.
 */
public class CatPost {

    private Long id;
    private String serverId;
    private String caption;
    private String image_url;
    private String userJson;
    private String commentsJson;

    public CatPost() {
    }

    public CatPost(Long id) {
        this.id = id;
    }

    public CatPost(Long id, String serverId, String caption, String image_url, String userJson, String commentsJson) {
        this.id = id;
        this.serverId = serverId;
        this.caption = caption;
        this.image_url = image_url;
        this.userJson = userJson;
        this.commentsJson = commentsJson;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getUserJson() {
        return userJson;
    }

    public void setUserJson(String userJson) {
        this.userJson = userJson;
    }

    public String getCommentsJson() {
        return commentsJson;
    }

    public void setCommentsJson(String commentsJson) {
        this.commentsJson = commentsJson;
    }

}
