package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CAT_POST.
 */
public class CatPost {

    private Long id;
    private String serverId;
    private String caption;
    private String image_url;
    private String user;
    private String comments;
    private String category;
    private Integer downloadCount;
    private Integer totalVotesCount;

    public CatPost() {
    }

    public CatPost(Long id) {
        this.id = id;
    }

    public CatPost(Long id, String serverId, String caption, String image_url, String user, String comments, String category, Integer downloadCount, Integer totalVotesCount) {
        this.id = id;
        this.serverId = serverId;
        this.caption = caption;
        this.image_url = image_url;
        this.user = user;
        this.comments = comments;
        this.category = category;
        this.downloadCount = downloadCount;
        this.totalVotesCount = totalVotesCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getDownloadCount() {
        return downloadCount;
    }

    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    public Integer getTotalVotesCount() {
        return totalVotesCount;
    }

    public void setTotalVotesCount(Integer totalVotesCount) {
        this.totalVotesCount = totalVotesCount;
    }

}
